services:
  openfusion:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: openfusion/openfusion:latest
    volumes:
      - ./config.ini:/usr/src/app/config.ini
      - ./database.db:/usr/src/app/database.db
      - ./tdata:/usr/src/app/tdata
    ports:
      - "23000:23000"
      - "23001:23001"
      - "8003:8003"
